# Generated by Django 4.0.2 on 2022-08-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(default='Неизвестен', verbose_name='Имя автора')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'объект Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='Международный стандартный книжный номер')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Аннотация')),
                ('year_release', models.PositiveSmallIntegerField(blank=True, verbose_name='Год выхода в свет')),
                ('copy_count', models.PositiveSmallIntegerField(default=1, verbose_name='Число копий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('year_publishing', models.PositiveIntegerField(blank=True, verbose_name='Год издания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='p_library.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'объект Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Неизвестно', verbose_name='Издательство')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
                ('city', models.CharField(default='unknown', max_length=25, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Читатель')),
                ('address', models.TextField(default='Планета Земля', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='BookReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now=True, null=True, verbose_name='Дата')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reading_reader', to='p_library.book', verbose_name='Сейчас читает:')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_reading_book', to='p_library.reader', verbose_name='Эту книгу сейчас читают:')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.publisher', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='reading_books', through='p_library.BookReader', to='p_library.Reader', verbose_name='Сейчас читают'),
        ),
    ]
